export App from './App'
export Home from './Home'
export Login from './Login'
export Register from './Register'
export Profile from './Profile'
export List from './List'
export DevTools from './DevTools'
export NotFound from './NotFound'