export const LOAD_ORDER = 'LOAD_ORDER';
export const LOAD_ORDER_SUCCESS = 'LOAD_ORDER_SUCCESS';
export const LOAD_ORDER_FAIL = 'LOAD_ORDER_FAIL';
export const LOAD_ORDER_BY_ID = 'LOAD_ORDER_BY_ID';
export const LOAD_ORDER_BY_ID_SUCCESS = 'LOAD_ORDER_BY_ID_SUCCESS';
export const LOAD_ORDER_BY_ID_FAIL = 'LOAD_ORDER_BY_ID_FAIL';

